inherit_from:
  - https://raw.githubusercontent.com/facebook/chef-cookbooks/main/.rubocop.yml

# TODO - ratchet lint into place
Style/GlobalStdStream:
  Enabled: false

# TODO - ratchet lint into place
Gemspec/RequiredRubyVersion:
  Enabled: false
